### ISSUE TITLE
Notifications/mentions broken by switching between the two

### ISSUE THREAD

**Issue by mxamber** [glitch-soc/mastodon#1823] opened 2022-08-07 16:15 UTC
### Steps to reproduce the problem

1. Get a notification
2. Click on notifications
3. Quickly (<3-5s) click on Mentions tab
...

### Expected behaviour

Toggling between notifications and mentions shouldn't be a problem

### Actual behaviour

Switching to the mentions tab too quickly causes both notifications and mentions tabs to empty and remain empty until page is reloaded (F5)

### Specifications

Occured on Mastodon 3.5.2+glitch using Firefox 103. Failed to reproduce on a vanilla Mastodon instance, so doesn't appear to be an upstream problem.

**Comment by ClearlyClaire** [comment] 2022-08-07 16:32
Is that using the single-column interface or the “advanced interface”? By switching to “mentions tab”, do you mean using the quick filter bar of the notification column?

**Comment by mxamber** [comment] 2022-08-07 21:16
Single-column interface and yes I think so.

![image](https://user-images.githubusercontent.com/13611718/183311263-3788d5f6-6275-4532-a8fc-8b5bc605a09f.png)

**Comment by ClearlyClaire** [comment] 2022-08-11 13:44
Thanks for the information. I can't reproduce it and I doubt this is a glitch-soc-specific bug. This needs more investigating, but my current guess is that the following happens: the processed notifications are those from the “All” query and happen to not contain any mention (because the first notification page only has notifications of different pages).

**Comment by mxamber** [comment] 2022-08-11 16:56
> I doubt this is a glitch-soc-specific bug

It only happens to me on glitch-soc and not on vanilla instances, though.

> the processed notifications are those from the “All” query and happen to not contain any mention

I've found the same issue also happens if I open notifications and quickly click on the notifications column, then all notifications (not just mentions) disappear as well. And if I click on mentions, all mentions disappear, including old ones, not just unread ones.

**Comment by ClearlyClaire** [comment] 2022-08-11 17:04
I can't quite reproduce what you're describing, but I'm managing to reproduce something close: quickly switching between two “incompatible” tabs leads to the notifications being empty. This occurs both with glitch and vanilla flavors. I think it's indeed because the interface uses the results from the first query to populate the notifications, which are then filtered using the current view: that is, clicking “favourites” then “mentions” in quick succession fills the list with favourites but the display filters it to only show mentions, and since there is no overlap, that's empty.

I'll try to write a fix.

**Comment by ClearlyClaire** [comment] 2022-08-11 18:21
This is indeed an upstream issue (which we inherit because we share that part of the code), so I wrote upstream PR #18960 to fix it.

As with all changes to code shared with upstream, I will port the fix when it is merged in upstream (this is in order to keep unintended divergences to a minimum and keep maintaining the fork manageable).

**Comment by ClearlyClaire** [comment] 2022-08-25 04:23
Upon further testing, it seems that while the fix I submitted upstream helps, it isn't enough: if the first request finishes after the second, its results will overwrite the list, effectively leading to an empty list after filtering (the bug used to occur whenever clicking before the first query completed, now it occurs if the queries complete out-of-order, which is less likely but still likely when e.g. switching from mentions to favs, as the former request is slower). Reopening.

**Closed** 2022-08-25 17:30 UTC
Labels: bug
