### ISSUE TITLE
Glitch light theme makes some text very pale on white backgrounds 

### ISSUE THREAD

**Issue by paralithode** [glitch-soc/mastodon#628] opened 2018-08-10 02:15 UTC
Here's side-by-side screenshots of the same post opened in stand alone view. On the left is the standard mastodon (light) flavour, & on the right is the glitch version of the mastodon (light) flavour. I feel like the text on the right is very pale and pretty difficult to read. I think it would be better if it looked more like the darker text in the standard light flavour.

![screenshot 2018-08-10 03 04 04](https://user-images.githubusercontent.com/24278481/43935058-1d99143c-9c4a-11e8-9d00-30100cadb6af.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment] 2018-09-04 14:01
I can't reproduce it, and I just merged a new version of the light theme with better contrast overall.
Please reopen if this is still an issue!

**Closed by ThibG** 2018-09-04 14:01 UTC
