### ISSUE TITLE
Add optional expiration time to mutes (and other actions)

### ISSUE THREAD

**Issue by KitRedgrave** [glitch-soc/mastodon#203] opened 2017-10-27 18:41 UTC
It would be nice if mutes, currently permanent until you think of removing them, could expire on their own. This could apply to user mutes, keyword mutes, and possibly conversation mutes.

This same logic could also apply to expiring posts, follows, blocks, and other actions depending on what we decide on.

It looks like these things would be part of it:
* A database table for tracking expiration records
* A Sidekiq cron job to actually delete/otherwise undo these actions
* UI changes to expose controls to add expiration times
* API changes for bots and external client apps to add expiration times

**Comment by marrus-sh** [comment] 2018-01-09 00:03
This is a duplicate of #118 so I'll close this and let's redirect discussion there~

**Closed by marrus-sh** 2018-01-09 00:03 UTC
Labels: enhance, feature expansion
