### ISSUE TITLE
Notification clearing autoscrolls notifs column to top

### ISSUE THREAD

**Issue by dexamphetamine** [glitch-soc/mastodon#331] opened 2018-01-17 03:58 UTC
If you scroll the notifications column down and then click the eraser icon to start selecting notifications to clear, the column autoscrolls back up to the top. If someone has thought to do the clearing process by scrolling to the notification first and clicking the eraser to switch to clearing mode second, this results in them losing their place.

(Found this behavior in Firefox 57.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment] 2018-01-17 04:16
ooh must be an event propagation error with the column headers i'll have to take a look

**Comment by ThibG** [comment] 2018-05-22 09:49
Is this still occurring? I can't reproduce it.

**Comment by ThibG** [comment] 2018-08-29 12:31
Closing as I have been unable to reproduce it for a while. Please reopen if it still occurs.

**Closed by ThibG** 2018-08-29 12:31 UTC
