### ISSUE TITLE
500 error on /about ("ERROR:  column accounts.suspended does not exist")

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1051] opened 2019-05-17 20:35 UTC
We're throwing 500 errors on the unauthenticated /about page:

```
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156] method=GET path=/about format=html controller=AboutController action=show status=500 error='ActionView::Template::Error: PG::UndefinedColumn: ERROR:  column accounts.suspended does not exist
web_2                                | LINE 1: ...count_stats"."account_id" = "accounts"."id" WHERE "accounts"...
web_2                                |                                                              ^
web_2                                | HINT:  Perhaps you meant to reference the column "accounts.suspended_at".
web_2                                | : SELECT  "accounts".* FROM "accounts" INNER JOIN "account_stats" ON "account_stats"."account_id" = "accounts"."id" WHERE "accounts"."suspended" = $1 AND "accounts"."moved_to_account_id" IS NULL AND "accounts"."silenced" = $2 AND "accounts"."discoverable" = $3 AND "account_stats"."followers_count" >= 10 ORDER BY account_stats.followers_count desc LIMIT $4' duration=68.89 view=0.00 db=5.49
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]   
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156] ActionView::Template::Error (PG::UndefinedColumn: ERROR:  column accounts.suspended does not exist
web_2                                | LINE 1: ...count_stats"."account_id" = "accounts"."id" WHERE "accounts"...
web_2                                |                                                              ^
web_2                                | HINT:  Perhaps you meant to reference the column "accounts.suspended_at".
web_2                                | : SELECT  "accounts".* FROM "accounts" INNER JOIN "account_stats" ON "account_stats"."account_id" = "accounts"."id" WHERE "accounts"."suspended" = $1 AND "accounts"."moved_to_account_id" IS NULL AND "accounts"."silenced" = $2 AND "accounts"."discoverable" = $3 AND "account_stats"."followers_count" >= 10 ORDER BY account_stats.followers_count desc LIMIT $4):
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     26:                 %small= t('about.browse_directory')
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     27: 
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     28:               .avatar-stack
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     29:                 - @instance_presenter.sample_accounts.each do |account|
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     30:                   = image_tag current_account&.user&.setting_auto_play_gif ? account.avatar_original_url : account.avatar_static_url, width: 48, height: 48, alt: '', class: 'account__avatar'
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     31: 
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]     32:         - if Setting.timeline_preview
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156]   
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156] app/views/about/show.html.haml:29:in `block in _app_views_about_show_html_haml___2187608321561504751_70351309742860'
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156] app/helpers/home_helper.rb:62:in `optional_link_to'
web_2                                | [7055e087-1a08-4c62-989f-ec61383a8156] app/views/about/show.html.haml:22:in `_app_views_about_show_html_haml___2187608321561504751_70351309742860'
```

This is very likely related to 14f6ce2885f7999f2fcbbdda6241a035271076d4 ... going to see if I can fix it up.  Will advise.  :)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by rtucker** [comment] 2019-05-17 20:41
FYI: looks like `docker-compose run --no-deps --rm web tootctl cache clear` fixed it, if anyone else runs into similar issues

**Comment by ThibG** [comment] 2019-05-17 21:53
Yeah, clearing cache might be needed after db changes. That is kinda expected and goes away after at most 10 minutes (when the cache expires).

I'm closing as not a bug, but it'd be nice if we had a better way to do this.

**Closed by ThibG** 2019-05-17 21:53 UTC

**Comment by rtucker** [comment] 2019-05-17 22:17
Awesome, I'm going to update my deploy scripts to do this automagically.

FWIW it was throwing it for about an hour before I fixed cleared the cache, so that was weird
