### ISSUE TITLE
Sending toots with media attachments fail in the webapp

### ISSUE THREAD

**Issue by Roxxers** [glitch-soc/mastodon#1050] opened 2019-05-16 01:26 UTC
I can't really find the reason for this but I copy pasted the error that is produces in firefoxs console. I don't remember the issue also being on vanilla masto before I moved over.

```
TypeError: t is undefined[Learn More] compose_form_container.js:127:6
    onMediaDescriptionConfirm compose_form_container.js:127
    e compose_form.js:130
    e button.js:26
    React 13
    Sn (index):1018
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment] 2019-05-16 08:08
I can't reproduce it, seems like a duplicate of #1040, which was fixed in #1041. Please reopen if it still happens after updating the instance!

**Closed by ThibG** 2019-05-16 08:08 UTC
