### ISSUE TITLE
Unread count on Notifications badge persists after checking notifications, web client (desktop/mobile) - at log-in or page refresh

### ISSUE THREAD

**Issue by mxkris** [glitch-soc/mastodon#1303] opened 2020-03-15 17:06 UTC
See image. On every page refresh or fresh log-in, (15) appears next to notifications.

Users on other instances have reported the same behavior with glitch-soc

![Annotation 2020-03-15 130551](https://user-images.githubusercontent.com/24760316/76706423-bc2ae000-66bd-11ea-8f33-5e6551bdbf91.png)

* * * *

- [ yes ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ no ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment] 2020-03-15 18:02
This should have been fixed a good while ago, but considering #1302 you probably aren't running up-to-date front-end code. Keeping open just in case though.

**Comment by mxkris** [comment] 2020-03-15 19:12
#1302 is clear, this issue persists.

**Comment by ThibG** [comment] 2020-03-15 19:39
I cannot reproduce this. Have you restarted mastodon-web since you recompiled assets? Have you reloaded the WebUI since then?

**Comment by mxkris** [comment] 2020-03-15 20:13
Yes and yes, tried desktop and mobile, incognito mode too.

**Comment by ThibG** [comment] 2020-03-15 20:14
Have you actually checked out the notifications before reloading?

**Comment by mxkris** [comment] 2020-03-15 20:44
Yes, I have. I also never get notifications in this amount.

**Comment by ThibG** [comment] 2020-03-15 21:19
what browser(s) are you using?

**Comment by mxkris** [comment] 2020-03-15 22:41
And after perpetuation across firefox and chrome for a few hours, it has stopped / slef-corrected. I'm thinking even with incognito mode, something bad was cached. I don't know. I'll re-open if the issue returns with consistency.

Thank you kindly for your time.

**Comment by mxkris** [comment] 2020-03-16 12:32
Sorry to re-open and take more of your time, but things have gotten, strange.

So, the issue appears to be oddly intermittent, but can be reproduced:
If I get new notifications, I'll continue see a count of notifications on page refresh even after checking them.

This will persist across both chrome for desktop and mobile.

However, if I open my instance in Firefox and check my notifications, they clear permanently. I refresh my page in Chrome after interacting using Firefox and the notifications permanently clear.

Perhaps there is something to do with Chrome not properly sending the "user has checked notifications" event to clear the notification count badge?

**Comment by mxkris** [comment] 2020-03-16 12:40
This is no longer intermittent and can be reproduced.
Reproduction instructions:
- Receive notification, open instance in Chrome
- Go to notifications tab, badge count clears. Refresh page, badge returns with previous count.
- Open instance in Firefox, check notifications, badge clears, refresh page, badge stays cleared
- Open Chrome, refresh page, badge counter does not return

**Comment by ashkitten** [comment] 2020-03-16 16:50
i'm pretty sure chrome just doesn't allow asynchronous requests in the beforeunload handler (which is how notification read markers are sent, for some reason). i have the same issue because i use firefox on my desktop but chrome for the pwa on my phone.

really what needs to happen, as i've discussed with @ThibG on discord, is that we should have it send read marker updates immediately but throttled to every 30 seconds or so

**Comment by koyuawsmbrtn** [comment] 2020-05-29 17:02
Can confirm this on my instance as well. This has been an annoying bug since forever now.

**Comment by ThibG** [comment] 2020-05-29 17:20
It's because the way Mastodon (and glitch-soc) updates the markers doesn't work with Chromium. I am trying to improve that upstream (https://github.com/tootsuite/mastodon/pull/13887, https://github.com/tootsuite/mastodon/pull/13889) and will port it to glitch-soc as soon as it is done.

**Comment by ThibG** [comment] 2020-05-29 20:13
Should be fixed with last merge

**Closed by ThibG** 2020-05-29 20:13 UTC
