### ISSUE TITLE
Some toots from ephemeral.glitch.social are not getting deleted from dev.glitch.social

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#340] opened 2018-01-20 06:30 UTC
I can't find a pattern, but - some of the posts are weeks or months old but are showing up on my ephemeral profile as seen from dev.glitch, some are showing up in hashtag searches. Some are replies and some aren't. Some are in threads and some aren't. Some have CWs and some don't. I can click to expand. I can save/fave an ephemeral post and it shows up in my dev.glitch.social faves list. When I boost, it's **not** visible to my cybre.space account that's following my dev.glitch account.

I already talked to Bea about this but I just realised I should probably post it here too!

![screen shot 2018-01-20 at 07 18 58](https://user-images.githubusercontent.com/6607512/35180513-55f390c8-fdb2-11e7-9ad4-61325d68ef49.png)

My ephemeral account: `@cassolotl@ephemeral.glitch.social` http://ephemeral.glitch.social/@cassolotl

Edit: I use all kinds of post privacy settings, but as far as I can see all the not-deleted posts are public. (Thanks, dev.glitch exposure indicators! 😄 )

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment] 2019-01-11 14:03
@thibg seems like this was closed by accident when you merged master

**Comment by ThibG** [comment] 2019-01-11 18:20
Oops indeed!

**Comment by ThibG** [comment] 2019-01-11 18:22
I don't believe the ephemeral code is in glitch-soc?
I have noticed some deleted toots not being deleted, though, and I haven't found the cause for that yet.

**Closed** 2022-10-08 15:08 UTC
