### ISSUE TITLE
text sometimes overlaps visibility icons with new collapsed notifications

### ISSUE THREAD

**Issue by chriswmartin** [glitch-soc/mastodon#393] opened 2018-03-18 02:16 UTC
After #386 if a user has a long display name the "... favourited your status" text will overlap toot visibility icons.

![screenshot 2018-03-17 at 9 06 11 pm](https://user-images.githubusercontent.com/17181697/37561887-549f07fa-2a28-11e8-913f-7b2307560253.png)
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment] 2018-03-18 02:41
@ashkitten Do you know offhand what the likely cause of this is?

**Comment by ashkitten** [comment] 2018-03-18 11:17
oof, yeah. the fix I committed makes the icon position absolute.

**Comment by ashkitten** [comment] 2018-03-18 11:19
It was the simplest way to fix it, and I've got no idea how to position it otherwise >.<

**Comment by yipdw** [comment] 2018-03-18 16:52
I'm not sure if it's the icon causing the problem, though.  It looks like the span is intrinsically too large:

![screenshot_20180318_115034](https://user-images.githubusercontent.com/3859/37568405-acf42e06-2aa2-11e8-901a-2016e0313276.png)

But maybe we really want something like this (maybe not necessarily with margins, but you get the idea):

![screenshot_20180318_115108](https://user-images.githubusercontent.com/3859/37568408-b4ba36ee-2aa2-11e8-9662-2843b525efbb.png)

@marrus-sh wrote the status component; maybe she knows of a better way than slapping `margin-right:` on elements?

**Comment by ashkitten** [comment] 2018-03-18 17:28
The problem is that the icon is generally in-line with the status text, but my setting it to use `position: absolute` took it out of the flow, so it doesn't affect the status text width anymore.

**Comment by marrus-sh** [comment] 2018-03-18 21:53
Yeah this is why i didn't have the icons up there initially…

Probably the easiest approach would just be to stick the icons in the prepend if it exists, and in the header if not, using either flexboxes or floats to shrink the remaining space as required

Setting margins/padding is iffy because the number of icons can be as small as 1 or as large as 3, depending

**Comment by marrus-sh** [comment] 2018-03-18 21:56
(looking at your PR it looks like that's what you did? so ^_^)

**Comment by yipdw** [comment] 2018-03-19 03:24
@chriswmartin AFAIK this is still an open issue on master? I'm not sure why you closed it.

**Comment by chriswmartin** [comment] 2018-03-19 03:30
@yipdw oops, for some reason I thought #393 was merged

**Comment by ThibG** [comment] 2018-05-20 10:04
I believe this to be fixed? Please reopen if needed.

**Closed by ThibG** 2018-05-20 10:04 UTC
