### ISSUE TITLE
We can't send emails now

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#330] opened 2018-01-16 04:48 UTC
i got this error on sidekiq page

> ActionView::Template::Error: Webpacker can't find mailer.css in /home/mastodon/live/public/packs/manifest.json. Possible causes: 1. You want to set webpacker.yml value of compile to true for your envir...

this error occurs for all email types
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment] 2018-01-16 05:25
cda845ae0e731a0ac3e7e58235c99cbbf93dda69 and 60ff0869603c80fbaae407e492e0e7f60e2e40e6 should fix this; let me know if it doesn't

**Comment by marrus-sh** [comment] 2018-01-16 05:27
(this bug was caused by https://github.com/tootsuite/mastodon/pull/6256)

**Comment by ncls7615** [comment] 2018-01-16 05:43
yes fixed
but images link are does not work...
![image](https://user-images.githubusercontent.com/28977652/34973521-70f63860-facb-11e7-82da-0733eb96098f.png)

**Comment by marrus-sh** [comment] 2018-01-18 23:56
this appears to be solved by tootsuite#6264

so it should be fixed when we merge in #332

**Comment by yipdw** [comment] 2018-01-23 16:27
Is this fixed?

**Comment by ncls7615** [comment] 2018-01-23 16:38
yes fixed~

**Closed** 2018-01-23 16:38 UTC
