### ISSUE TITLE
markdown link title gets ignored

### ISSUE THREAD

**Issue by RiedleroD** [glitch-soc/mastodon#2367] opened 2023-08-13 13:36 UTC
### Steps to reproduce the problem

1. write a toot with footnote (or link) like for example
```md
You do not recognize [the bodies in the water][1].

[1]: https://scp-wiki.wikidot.com/scp-2316 "SCP article [CW: cosmic horror, text only]"
```
or, as a regular link
```md
You do not recognize [the bodies in the water](https://scp-wiki.wikidot.com/scp-2316 "SCP article [CW: cosmic horror, text only]").
```
3. post the toot & have a look at the html output
...

### Expected behaviour

the title attribute is set to the title I set

### Actual behaviour

the title I set is completely ignored and the attribute is set to the link

### Detailed description

some potentially interesting references I found:
- https://github.com/vmg/redcarpet/pull/271
- https://daringfireball.net/projects/markdown/syntax#link

I just hope this isn't an upstream issue.

### Mastodon instance

catcatnya.com

### Mastodon version

v4.1.4+glitch+cat+1.0.0

### Browser name and version

116.0.2

### Operating system

Arch Linux 6.4.8 with Sway

### Technical details

![image](https://github.com/glitch-soc/mastodon/assets/57227431/b6ef1d8c-3415-4d9f-9e5a-a753097608ff)

Yes I'm not using pure glitch-soc, but catstodon only makes small changes, and my userstyle can't change the DOM. I'm 90% sure this is reproducible on your master branch.

**Comment by Plastikmensch** [comment] 2023-08-13 14:08
Footnotes are not supported on purpose currently.
I'm not sure if there is a specific reason for that or not.

Unfortunately it kinda is an upstream issue.
Because links are truncated in toots, the title attribute is supposed to show the full URL.
Setting your own title is not supported.

**Comment by RiedleroD** [comment] 2023-08-13 15:07
alright, so close as not planned or keep open for future reference?

**Comment by Plastikmensch** [comment] 2023-08-13 15:23
As this is unfortunately not a bug, I think closing it is the best choice.

**Closed** 2023-08-14 12:23 UTC
Labels: bug
