### ISSUE TITLE
Stylus customs css/styles do not apply anymore

### ISSUE THREAD

**Issue by keltia** [glitch-soc/mastodon#989] opened 2019-04-14 11:46 UTC
[Issue text goes here].

Hello,

I'm on both `mastodon.social` and `bsd.network`, the latter use glitch-soc now.  I have two "styles" added through the Firefox extension called Stylus, one for the colours of the theme and the second one for using all the available space for all three colums?

See: https://www.dropbox.com/s/fjk5byczpydrzsy/Screenshot%202019-04-14%2013.43.10.png?dl=0

Now that bsd.network has moved to glitch-soc, the second one for enlarging the columns does not work anymore.  As the URL has not changed (still bsd.network), I guess there have been either an embedded url or some css changes that invalidate it. 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment] 2019-04-14 11:51
There are indeed CSS changes, as the front-end has diverged quite a bit.
As I don't know the contents of those user styles, I am not sure what needs to be changed.
For the wide columns, you may want to check the app settings, which have an option for wider columns, although this merely increases their max size and does not necessarily make them stretch all the way.

**Comment by keltia** [comment] 2019-04-14 12:06
This is the one I'm using.
https://userstyles.org/styles/139721/mastodon-glitch-soc-variable-width

Wide view is already enabled on `bsd.network` apparently.

**Comment by ThibG** [comment] 2019-04-14 12:51
I haven't installed Stylus and tried the userstyle itself yet but it appears to work properly on my glitch-soc instance, when manually copying the contents of the userstyle in Firefox's style editor.

**Comment by ThibG** [comment] 2019-04-14 17:14
I installed it and I can confirm this works when adding my domain in the list of domains it should apply to.

**Comment by ThibG** [comment] 2019-08-20 16:03
Closing, as I cannot reproduce this. Feel free to reopen if needed.

**Closed by ThibG** 2019-08-20 16:03 UTC
