### ISSUE TITLE
HTTP::ConnectionError on DownloadMediaWorker with http_proxy

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1600] opened 2021-09-09 02:11 UTC
### Expected behaviour

download remote media and showed on local web

### Actual behaviour

Sidekiq failed

### Steps to reproduce the problem

1. `MediaAttachment.find(id).download_file!`
2. Failed with HTTP::ConnectionError
3.
...

### Specifications

using commit 4a94f4127

**Comment by tribela** [comment] 2021-09-09 02:14
It is only happened when `http_proxy` env var is set

**Comment by tribela** [comment] 2021-09-09 02:34
`Request.new(:head, 'https://httpbin.org/get').perform` also raises an error.
But `Request.new(:head, 'http://httpbin.org/get').perform` is not. (https → http)

**Comment by ClearlyClaire** [comment] 2021-09-09 13:15
This issue is reproducible with upstream's codebase too. Furthermore, this seems to be an issue with the `http` gem.

Indeed, `HTTP.via('127.0.0.1', 8118).get('http://httpbin.org/get')` works but `HTTP.via('127.0.0.1', 8118).get('https://httpbin.org/get')` does not.

This also seems to be a regression as it works with the `http` gem in version 4.4.

**Comment by ClearlyClaire** [comment] 2021-09-21 15:50
Fixed by updating the `http` gem.

**Closed by ClearlyClaire** 2021-09-21 15:50 UTC
Labels: bug
