### ISSUE TITLE
User-accessible list of all user-level domain blocks

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#233] opened 2017-11-30 04:22 UTC
There should be a way to list all user-level domain blocks.  As far as I can tell, it's possible for a user to block a domain, but there isn't a page to list those blocks (which makes it hard to review or undo the blocks).

This could probably be a part of the preferences page for now.

**Comment by yipdw** [comment] 2017-11-30 16:40
@beatrix-bitrot has pointed out that this would probably be better suited for the "*" menu:

![screenshot_20171130_104017](https://user-images.githubusercontent.com/3859/33442488-e2b89a82-d5ba-11e7-9e42-2326de2879b8.png)

**Comment by yipdw** [comment] 2017-11-30 16:47
There's already an API endpoint for this at `/api/v1/domain_blocks`; maybe this list really _does_ exist in the frontend and it's just hard to find?

**Comment by yipdw** [comment] 2017-11-30 16:49
Hmm, guess not:

```
$ grep -R domain_blocks *
mastodon/features/account_timeline/containers/header_container.js:import { blockDomain, unblockDomain } from '../../../actions/domain_blocks';
mastodon/reducers/relationships.js:} from '../actions/domain_blocks';
mastodon/actions/domain_blocks.js:    api(getState).post('/api/v1/domain_blocks', { domain }).then(() => {
mastodon/actions/domain_blocks.js:    api(getState).delete('/api/v1/domain_blocks', { params: { domain } }).then(() => {
themes/glitch/features/account_timeline/containers/header_container.js:import { blockDomain, unblockDomain } from 'themes/glitch/actions/domain_blocks';
themes/glitch/reducers/relationships.js:} from 'themes/glitch/actions/domain_blocks';
themes/glitch/actions/domain_blocks.js:    api(getState).post('/api/v1/domain_blocks', { domain }).then(() => {
themes/glitch/actions/domain_blocks.js:    api(getState).delete('/api/v1/domain_blocks', { params: { domain } }).then(() => {
```

There's no `api(getState).get('/api/v1/domain_blocks')`.

**Comment by marrus-sh** [comment] 2017-12-10 01:15
This is a duplicate of #86 I'm pretty sure, so I'll close this one and we can move discussion there.

**Closed by marrus-sh** 2017-12-10 01:15 UTC
Labels: duplicate, enhance, new feature
