### ISSUE TITLE
Bad @instance name with Glitch to Misskey

### ISSUE THREAD

**Issue by kazukyakayashi** [glitch-soc/mastodon#1304] opened 2020-03-22 07:27 UTC
Hi,

From Misskey, when a person under Glitch-Soc writes a message or answers me, the name of the instance of the people in the conversation is automatically replaced by the name of the person under Glitch.

Reply example, (me on Misskey @meow.zarchbox.fr)
![glitch-soc-bug](https://user-images.githubusercontent.com/39823221/77244547-31466a00-6c16-11ea-94c5-c4f3551f87b9.JPG)

This problem only occurs with people under Glitch-Soc, no problem with Mastodon, Pleroma, Hubzilla or other social platform.

Issues on Misskey : https://github.com/syuilo/misskey/issues/6177

**Comment by ThibG** [comment] 2020-03-22 14:36
From the Misskey issue, this seems to be a Misskey bug caused by an issue in glitch-soc (#1281). I need to find a way to fix that issue, hm…

**Comment by ThibG** [comment] 2020-03-24 11:08
Should be fixed by #1306

**Closed by ThibG** 2020-03-24 11:08 UTC
