### ISSUE TITLE
"Request archive" never successfully creates an archive

### ISSUE THREAD

**Issue by JacksonChen666** [glitch-soc/mastodon#2233] opened 2023-05-25 09:13 UTC
### Steps to reproduce the problem

1. Request an archive
2. See "Compiling your archive" after clicking the button.
3. Later, refresh and see there is no more entry.
4. Be confused

### Expected behaviour

An archive is created on request and delivered

### Actual behaviour

An archive is never created, and requests for archives disappear.

### Detailed description

The archive request seems to be silently dropped after spending some time processing.

Logs Note: From mastodon-sidekiq, some stuff was replaced. (I do not believe that keeping those things (hostname and keys) verbatim was necessary for this issue.)

Potentially helpful hint: Search for "NameError" in the logs

```
May 25 10:42:54 $hostname bundle[1008]: 2023-05-25T08:42:54.654Z pid=1008 tid=sx98 class=BackupWorker jid=4b26148aaebcbeaadfde3091 INFO: start
May 25 10:43:21 $hostname bundle[1008]: 2023-05-25T08:43:21.413Z pid=1008 tid=sx98 class=BackupWorker jid=4b26148aaebcbeaadfde3091 elapsed=26.759 INFO: fail
May 25 10:43:21 $hostname bundle[1008]: 2023-05-25T08:43:21.413Z pid=1008 tid=sx98 WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"args":[11],"class":"BackupWorker","jid":"4b26148aaebcbeaadfde3091","created_at":1685003864.4547863,"enqueued_at":1685004174.6542175,"error_message":"undefined local variable or method `tar' for #<BackupService:0x00007fde6b6fe7e8 @_routes=nil, @backup=#<Backup id: 11, user_id: 1, dump_file_name: nil, dump_content_type: nil, dump_updated_at: nil, processed: false, created_at: \"2023-05-25 08:37:44.448126000 +0000\", updated_at: \"2023-05-25 08:37:44.448126000 +0000\", dump_file_size: nil>, @account=#<Account id: 107339329861324539, username: \"jacksonchen666\", domain: nil, private_key: \"-----BEGIN RSA PRIVATE KEY-----\\AAAAAAAAAAAAAAAAAAA...\", public_key: \"-----BEGIN PUBLIC KEY-----\\nAAAAAAAAAAAAAAAAAAAAAAA...\", created_at: \"2021-11-25 19:23:12.340390000 +0000\", updated_at: \"2023-05-16 14:57:32.435041000 +0000\", note: \"gonna put something here later\", display_name: \"jackson :antiverified:\", uri: \"\", url: nil, avatar_file_name: \"a90cc3eba1ac2df4.gif\", avatar_content_type: \"image/gif\", avatar_file_size: 454087, avatar_updated_at: \"2022-12-10 21:16:07.771318000 +0000\", header_file_name: \"90d525503a9d8da4.jpeg\", header_content_type: \"image/jpeg\", header_file_size: 85659, header_updated_at: \"2022-04-19 08:39:38.902365000 +0000\", avatar_remote_url: nil, locked: true, header_remote_url: \"\", last_webfingered_at: nil, inbox_url: \"\", outbox_url: \"\", shared_inbox_url: \"\", followers_url: \"\", protocol: \"ostatus\", memorial: false, moved_to_account_id: nil, featured_collection_url: nil, fields: [{\"name\"=>\"site\", \"value\"=>\"https://jacksonchen666.com\", \"verified_at\"=>\"2021-12-13T07:18:22.913Z\"}, {\"name\"=>\"other accounts\", \"value\"=>\"https://jacksonchen666.com/misc/accounts/\", \"verified_at\"=>\"2023-05-14T07:59:26.679Z\"}], actor_type: \"Person\", discoverable: false, also_known_as: nil, silenced_at: nil, suspended_at: nil, hide_collections: true, avatar_storage_schema_version: 1, header_storage_schema_version: 1, devices_url: nil, suspension_origin: nil, sensitized_at: nil, trendable: nil, reviewed_at: nil, requested_review_at: \"2023-03-26 09:31:59.875818000 +0000\">>","error_class":"NameError","failed_at":1685003901.321116,"retry_count":3,"error_backtrace":"eJydjssOwiAQRX9Fu+lGmbY+Fv0VYyoDoyUFhkBpol8vqW7duJtzk3vuXCoY\n2RE4mWbW7MGahUCGAIniYhQlQKmmHIYvi4h92xx74zc3nV0YpJo5butq94/p\n3K4itKymTbkwG6sHGdVYyj+lC3nNETB7bQlixiccRCcaeJBLK79M2HeihKWA\nUAjuxn5+707rJAfydXV9A0ZwWiA=\n","retried_at":1685004074.491454}}
May 25 10:43:21 $hostname bundle[1008]: 2023-05-25T08:43:21.414Z pid=1008 tid=sx98 WARN: NameError: undefined local variable or method `tar' for #<BackupService:0x00007fde675184c8 @_routes=nil, @backup=#<Backup id: 11, user_id: 1, dump_file_name: nil, dump_content_type: nil, dump_updated_at: nil, processed: false, created_at: "2023-05-25 08:37:44.448126000 +0000", updated_at: "2023-05-25 08:37:44.448126000 +0000", dump_file_size: nil>, @account=#<Account id: 107339329861324539, username: "jacksonchen666", domain: nil, private_key: "-----BEGIN RSA PRIVATE KEY-----\nAAAAAAAAAAAAAAAAAA...", public_key: "-----BEGIN PUBLIC KEY-----\nAAAAAAAAAAAAAAAAAAAAAAA...", created_at: "2021-11-25 19:23:12.340390000 +0000", updated_at: "2023-05-16 14:57:32.435041000 +0000", note: "gonna put something here later", display_name: "jackson :antiverified:", uri: "", url: nil, avatar_file_name: "a90cc3eba1ac2df4.gif", avatar_content_type: "image/gif", avatar_file_size: 454087, avatar_updated_at: "2022-12-10 21:16:07.771318000 +0000", header_file_name: "90d525503a9d8da4.jpeg", header_content_type: "image/jpeg", header_file_size: 85659, header_updated_at: "2022-04-19 08:39:38.902365000 +0000", avatar_remote_url: nil, locked: true, header_remote_url: "", last_webfingered_at: nil, inbox_url: "", outbox_url: "", shared_inbox_url: "", followers_url: "", protocol: "ostatus", memorial: false, moved_to_account_id: nil, featured_collection_url: nil, fields: [{"name"=>"site", "value"=>"https://jacksonchen666.com", "verified_at"=>"2021-12-13T07:18:22.913Z"}, {"name"=>"other accounts", "value"=>"https://jacksonchen666.com/misc/accounts/", "verified_at"=>"2023-05-14T07:59:26.679Z"}], actor_type: "Person", discoverable: false, also_known_as: nil, silenced_at: nil, suspended_at: nil, hide_collections: true, avatar_storage_schema_version: 1, header_storage_schema_version: 1, devices_url: nil, suspension_origin: nil, sensitized_at: nil, trendable: nil, reviewed_at: nil, requested_review_at: "2023-03-26 09:31:59.875818000 +0000">>
May 25 10:43:21 $hostname bundle[1008]: 2023-05-25T08:43:21.414Z pid=1008 tid=sx98 WARN: /home/mastodon/live/app/services/backup_service.rb:104:in `dump_actor!'
May 25 10:43:21 $hostname bundle[1008]: /home/mastodon/live/app/services/backup_service.rb:61:in `block in build_archive!'
May 25 10:43:21 $hostname bundle[1008]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
```

No idea if this should be an upstream issue.

Issue might be at exactly [here](https://github.com/glitch-soc/mastodon/blob/b233da5996c7bfcf7a9373bdc7029feb04c704b8/app/services/backup_service.rb#L104) (includes commit, file, and line), and [hasn't changed](https://github.com/glitch-soc/mastodon/blob/054df2d67e61cdd78afa7b1c15fd61823c421620/app/services/backup_service.rb#L104) (includes current commit of instance, file and line).

### Specifications

Mastodon 054df2d67e61cdd78afa7b1c15fd61823c421620
Ruby `3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]`

**Comment by Plastikmensch** [comment] 2023-05-25 10:12
Yup, these lines should've been:
```ruby
download_to_zip(zipfile, account.avatar, "avatar#{File.extname(account.avatar.path)}") if account.avatar.exists?
download_to_zip(zipfile, account.header, "header#{File.extname(account.header.path)}") if account.header.exists?
```
`tar` was renamed to `zipfile`

**Comment by ClearlyClaire** [comment] 2023-05-25 10:48
This is a known bug fixed upstream. I will try to merge upstream changes sometime this week.

**Comment by ClearlyClaire** [comment] 2023-05-27 09:40
Hi! This should be fixed by the last upstream merge. Can you confirm that's working as intended?

**Closed as completed** 2023-05-27 09:47 UTC
Labels: bug
