### ISSUE TITLE
3 dot context menu appearing below media elements

### ISSUE THREAD

**Issue by cdmnky73** [glitch-soc/mastodon#1429] opened 2020-09-25 20:29 UTC
## Expected Behavior
The menu should appear above the media and text of the post when it's overtop of it.

## Actual Behavior
Menu appears below images, and in the case of hidden images appears above the blur and below the "sensitive content" text

![Screenshot_20200925_161712](https://user-images.githubusercontent.com/60628449/94312571-2664ed00-ff4b-11ea-80c5-1aba86c8b95f.png)
![Screenshot_20200925_161729](https://user-images.githubusercontent.com/60628449/94312586-2a910a80-ff4b-11ea-898d-8e79c31c35d6.png)
![Screenshot_20200925_161756](https://user-images.githubusercontent.com/60628449/94312589-2c5ace00-ff4b-11ea-9a18-eff75064ae20.png)

Tested on vulpine.club running v3.2.0+glitchfox-prod2020090401 while using Waterfox Current 2020.09

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

- [ ] This bug also occurs on vanilla Mastodon

**Comment by ThibG** [comment] 2020-09-25 20:39
Duplicate of #1420, should be fixed already.

**Closed by ThibG** 2020-09-25 20:39 UTC
