### ISSUE TITLE
Option to put mobile navigation bar to the top, instead of being a sidebar

### ISSUE THREAD

**Issue by tusooa** [glitch-soc/mastodon#2013] opened 2022-12-15 19:26 UTC
### Pitch

https://github.com/mastodon/mastodon/issues/19571 , and upstream does not want to do this.

### Motivation

On mobile platforms, the width is very limited, while the height is relatively abundant. Navigation bar should use the available space, not restrict the already insufficient space.

**Comment by Plastikmensch** [comment] 2022-12-15 19:33
Duplicate of #1898

**Closed** 2022-12-15 19:34 UTC
