### ISSUE TITLE
Sidekiq fills up queue 

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1711] opened 2022-03-03 12:57 UTC
### Steps to reproduce the problem

1. Update to latest code
2. Check sidekiq
3. Queue is filling up with threads
...

After the update from yesterday I noticed sidekiq was filling up the queue with tasks that kept failing it seems. Therefor I started 200 extra pull tasks yesterday in the hope it would be solved today but unfort not. 

Currently around the same amount is still in queue and it's effecting timelines. I have checked all logs but I can't find anything weird, it's processing the jobs. Also other users noticed mastodon.online has timeline issues also after last night, not sure that's part of it though.

No matter what I try the jobs keep filling (sorry for Dutch)

<img width="784" alt="Schermafbeelding 2022-03-03 om 13 56 26" src="https://user-images.githubusercontent.com/57602062/156569014-4874bd26-c7f0-4676-9b1a-8444129e2397.png">
up the queue. Can this be caused by a bug maybe? 

### Expected behaviour

Working those jobs

### Actual behaviour

It's acting up

### Specifications

Latest glitch-soc

**Comment by ClearlyClaire** [comment] 2022-03-03 13:02
I can't help without information about which tasks are failing or piling up.

**Comment by mstdn** [comment] 2022-03-03 13:09
Sorry, It's all but pull jobs.. 

Most pages are: ActivityPub::LowPriorityDeliveryWorker

Not really sure where and how I can get a better overview 

<img width="768" alt="Schermafbeelding 2022-03-03 om 14 07 43" src="https://user-images.githubusercontent.com/57602062/156570783-00a95d97-5c93-4d42-a649-9343e6f7f38b.png">

**Comment by ClearlyClaire** [comment] 2022-03-03 13:10
does not seem like a regression, just a lot of delete jobs being queued

**Comment by mstdn** [comment] 2022-03-03 15:59
Getting back to this, currently the local timeline won't load for me. It results in a 500 error:
<img width="493" alt="7addc770b0f54a07" src="https://user-images.githubusercontent.com/57602062/156601692-87fe5090-183c-486e-8ba5-18c7c326bc9d.png">

For a while https://mstdn.social/api/v1/timelines/public?local=true&only_media=false did result in "Something wrong from out end" but now seems to work again. But when I go back 2 or 3 "pages" down it again throws an 500. 

console log:
<img width="1081" alt="Schermafbeelding 2022-03-03 om 16 58 40" src="https://user-images.githubusercontent.com/57602062/156602117-583aea25-9a9b-4749-932d-ad1623841196.png">

**Comment by mstdn** [comment] 2022-03-03 16:11
> Can you run this SQL query?
> 
> ```sql
> SELECT id FROM statuses WHERE reblog_of_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM statuses r WHERE statuses.reblog_of_id = r.id);
> ```

Running it now. It takes some time it seems.. We do have a large db.

**Comment by ClearlyClaire** [comment] 2022-03-03 16:18
but you can still reproduce the issue? that's weird… I'm not sure how that could happen, but I'm going to investigate a bit more…

**Comment by mstdn** [comment] 2022-03-03 16:19
> but you can still reproduce the issue? that's weird… I'm not sure how that could happen, but I'm going to investigate a bit more…

For sure! Both in vanilla and Glitch but that's logical i guess. It happens everytime on a certain location on the local timeline. 

Like there's a post there that messes things up..

**Comment by ClearlyClaire** [comment] 2022-03-03 16:21
Can you edit `app/models/status.rb` and change `def reload_stale_associations!` so it reads like the following, reload `mastodon-web`, trigger the error again and check the logs?

```ruby
    def reload_stale_associations!(cached_items)
      account_ids = []

      cached_items.each do |item|
        account_ids << item.account_id
        Rails.logger.warn "DEBUG: #{item.reblog_of_id}" if item.reblog? && item.reblog.nil?
        account_ids << item.reblog.account_id if item.reblog?
      end

      account_ids.uniq!

      return if account_ids.empty?

      accounts = Account.where(id: account_ids).includes(:account_stat, :user).index_by(&:id)

      cached_items.each do |item|
        item.account = accounts[item.account_id]
        item.reblog.account = accounts[item.reblog.account_id] if item.reblog?
      end
    end
```

**Comment by mstdn** [comment] 2022-03-03 16:28
Can I find the debug ID somewhere? 

<img width="1440" alt="Schermafbeelding 2022-03-03 om 17 27 44" src="https://user-images.githubusercontent.com/57602062/156607628-464e12f3-6fde-47e7-bbe9-c2de6bc780e7.png">

**Comment by ClearlyClaire** [comment] 2022-03-03 16:29
Try the following queries:

```sql
SELECT created_at, deleted_at FROM statuses WHERE id = 107893375171922089;
SELECT id, created_at, deleted_at FROM statuses WHERE reblog_of_id = 107893375171922089;
```

**Comment by mstdn** [comment] 2022-03-03 16:31
<img width="865" alt="Schermafbeelding 2022-03-03 om 17 31 34" src="https://user-images.githubusercontent.com/57602062/156608334-ce3d7b7c-1e34-4dcd-a20f-81cef6db6807.png">

**Comment by ClearlyClaire** [comment] 2022-03-03 18:25
It probably is unrelated to your sidekiq jobs issue, though, but it's a rare race condition that original status to be marked as deleted while boosts came in and did not get marked as deleted.

I do not know a proper way to fix the call sites and I'm still investigating the race condition itself, but in the meantime you can do the following:

```sql
UPDATE "statuses" SET "deleted_at" = now() WHERE reblog_of_id = 107893375171922089;
```
```

**Comment by ClearlyClaire** [comment] 2022-03-04 00:19
The growing sidekiq queues might be because of wasteful and… infinite… forwarding of `Update` activities. Temporarily disabled in latest glitch-soc version.

**Comment by ClearlyClaire** [comment] 2022-03-10 16:30
Closing because both the `Update` forwarding and the reblog race condition have been fixed.

**Closed by ClearlyClaire** 2022-03-10 16:30 UTC
Labels: bug
