### ISSUE TITLE
Media gallery modal CSS broken

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#80] opened 2017-07-15 13:55 UTC
didn't find why, but our media gallery css is somehow broken
it stretches to huge size even for small images, and tiny images are scaled up and distorted
<s>have compared it with vanilla and it's our bug</s> edit: turns out actually an upstream regression from last tag

eg: this should not be so wide but enclose the image tightly
![screenshot_20170715_154935](https://user-images.githubusercontent.com/2041118/28239856-d09ccc26-6975-11e7-93bb-be8456a16842.png)

**Comment by beatrix-bitrot** [comment] 2017-07-20 13:50
i'm pretty sure this is in upstream since i get it on glitch.social also

**Comment by MightyPork** [comment] 2017-07-20 13:56
I checked on mastodon.xyz and it looked OK. if glitch.social is master, than yeah.. xyz is on a tag afaik

**Comment by beatrix-bitrot** [comment] 2017-07-20 14:02
yeah confirmed they're way out on glitch.social

**Comment by marrus-sh** [comment] 2017-12-10 00:41
Do we have thoughts on this now that the lightbox styling has changed somewhat? I don't think upstream really considers this a bug.

**Comment by ThibG** [comment] 2018-09-04 17:26
They're supposed to be at the sides of the screen, which is not quite like the screenshot shown above, but that was fixed.
Is that a behavior we want to change, or can we close this issue?

**Closed** 2019-08-20 16:04 UTC
Labels: bug, upstream bug
