### ISSUE TITLE
Glitch-soc interface does not reset language on Alt-N (but actually my UI is out of date)

### ISSUE THREAD

**Issue by JacksonChen666** [glitch-soc/mastodon#2247] opened 2023-06-10 14:52 UTC
### Steps to reproduce the problem

1. Start reply to a post in a non-default language (e.g. if your default is English, reply to a German post)
2. Alt-N (Compose new toot shortcut)

### Expected behaviour

Language choice should reset back to default

### Actual behaviour

Language choice does not reset to default

### Detailed description

Mastodon Vanilla UI does reset language back to default.

### Specifications

Mastodon d907e7914094cfbbd54c2662ff09a6113ed526e9

LibreWolf 113.0.2-1
macOS 13.4

**Comment by Plastikmensch** [comment] 2023-06-12 13:27
I can't reproduce this.
The issue you describe has been fixed in #2114
The shortcut just dispatches `COMPOSE_RESET`
Seems like you somehow miss that change.

**Comment by Plastikmensch** [comment] 2023-06-12 15:11
Ah yes, has been a known issue for a while

To force a compile:
`RAILS_ENV=production bundle exec rails assets:clobber`
and then
`NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production bundle exec rails assets:precompile`
Both run as the mastodon user

**Closed as completed** 2023-06-12 17:41 UTC
Labels: bug
