### ISSUE TITLE
Disabled boost icon does not show in Firefox

### ISSUE THREAD

**Issue by yiskah** [glitch-soc/mastodon#106] opened 2017-07-28 15:49 UTC
For some reason on posts in my notifications the buttons for interacting with a post get spread out all weird

![capture](https://user-images.githubusercontent.com/12243190/28725176-b0c4ca10-738a-11e7-88e4-50882240af61.JPG)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment] 2017-07-28 18:42
I can't seem to reproduce this

**Comment by yiskah** [comment] 2017-07-30 21:58
What's your screen resolution and browser? I'm on firefox for windows. This doesn't occur on my home computer which is 1600x1080. But my work computer has this issue, with 1366x768 as its resolution

**Comment by MightyPork** [comment] 2017-07-30 22:04
okay I think it's a firefox bug of some kind, it refuses to render the disabled boost SVG

**Comment by marrus-sh** [comment] 2017-09-20 09:05
Fixed with 003bfd0; the problem was that the hex color `#` in the SVG `data:` uri was interpreted (correctly iirc) as a fragment identifier.

**Closed by marrus-sh** 2017-09-20 09:05 UTC
Labels: bug
